version: "3.7"
services:

  mysql:
    image: mysql
    restart: on-failure
    ports: ['3306:3306']
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  adminer:
    depends_on:
      - mysql
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080
