#index:
#    path: /
#    controller: App\Controller\DefaultController::index



home:
    path: /
    controller: App\Controller\DefaultController::indexAction


skill:
    path: /skill
    controller: App\Controller\DefaultController::skillAction



techno:
    path: /techno
    controller: App\Controller\DefaultController::technoAction



project:
    path: /project
    controller: App\Controller\DefaultController::projectAction


daschboard:
    path: /daschboard
    controller: App\Controller\DaschboardController::daschAction


daschboard_choix:
    path: /daschboard/{name}
    controller: App\Controller\DaschboardAjoutController::daschAjoutAction


daschboard_update:
    path: /daschboard/update/{name}/{id}
    controller: App\Controller\DaschboardUpdateController::index


daschboard_delete:
    path: /daschboard/delete/{name}/{id}
    controller: App\Controller\DaschboardDeleteController::index







